### ISSUE TITLE
TypeError: %d format

### ISSUE THREAD

**Issue by TsviyaOlender** [arq5x/lumpy-sv#104]
Hi
I am trying to run lumpy of ~150 yeast genomes. For some of the samples I get the following error:
[danaba@molgen all_P]$ lumpyexpress -B remove/evoP1_P20.all.mdup.sort.bam -S remove/evoP1_P20.split.rdup.sort.bam -D remove/evoP1_P20.disc.rdup.sort.bam
Sourcing executables from /apps/RH6U4/lumpy/0.2.11/bin/lumpyexpress.config ...

Checking for required python modules (/apps/RH6U4/python/2.7.9/bin/python)...
Calculating insert distributions...
Library read groups: evoP1_P20
Library read length: 101
/apps/RH6U4/python/2.7.9/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/apps/RH6U4/python/2.7.9/lib/python2.7/site-packages/numpy/core/_methods.py:71: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/apps/RH6U4/lumpy/0.2.11/scripts/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64

Would you kindly advise?

**Comment by abolia** [comment]
I got the same error. Were you able to fix it @TsviyaOlender ?

Thanks, 
Ashini.

**Comment by TsviyaOlender** [comment]
Unfortunately, no.

**Comment by abolia** [comment]
Hi  @TsviyaOlender,

I think I figured out whats causing this error:

"  File "/home/u6001/tools/lumpy-sv/scripts/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64
"
This is coz the # of reads required to generate the empirical stats are lesser than the # reads in your bam file:

In more detail:
 
Here is the command I used to run:

~/tools/samtools view -r 24048-EWSR 24048-EWSR_Merged.bam | tail -n+100000 | /home/u6001/tools/lumpy-sv/scripts/pairend_distro.py -r 146 -X 4 -N 10000 -o 4048-EWSR 24048-EWSR_Merged.lib1.his

I figured out that this error is coz I only have 49680 reads in my bam file. And therefore I ran it again with "tail -n+10000" option:

~/tools/samtools view -r 24048-EWSR 24048-EWSR_Merged.bam | tail -n+10000 | /home/u6001/tools/lumpy-sv/scripts/pairend_distro.py -r 146 -X 4 -N 10000 -o 4048-EWSR 24048-EWSR_Merged.lib1.his

And this works perfectly fine. So, hopefully thats the same issue with you also. I see that you are running LumpyExpress which automatically generates the stats for you. So, in this case you might have to go and change the clues in the /scripts/lumpyexpress code which is set as "tail -n+1000000" and sample size "N= 1000000" Try checking how many reads you have in your BAM file and change that accordingly. 

Hope this helps. 
Ashini.

**Comment by ryanlayer** [comment]
@TsviyaOlender <https://github.com/TsviyaOlender>, can you check to see if
you are having the same file length issue?

On Tue, Dec 1, 2015 at 1:04 PM, abolia <notifications@github.com> wrote:

> Hi @TsviyaOlender <https://github.com/TsviyaOlender>,
>
> I think I figured out whats causing this error:
>
> " File "/home/u6001/tools/lumpy-sv/scripts/pairend_distro.py", line 106,
> in
> (removed, upper_cutoff))
> TypeError: %d format: a number is required, not numpy.float64
> "
> This is coz the # of reads required to generate the empirical stats are
> lesser than the # reads in your bam file:
>
> In more detail:
>
> Here is the command I used to run:
>
> ~/tools/samtools view -r 24048-EWSR 24048-EWSR_Merged.bam | tail -n+100000
> | /home/u6001/tools/lumpy-sv/scripts/pairend_distro.py -r 146 -X 4 -N 10000
> -o 4048-EWSR 24048-EWSR_Merged.lib1.his
>
> I figured out that this error is coz I only have 49680 reads in my bam
> file. And therefore I ran it again with "tail -n+10000" option:
>
> ~/tools/samtools view -r 24048-EWSR 24048-EWSR_Merged.bam | tail -n+10000
> | /home/u6001/tools/lumpy-sv/scripts/pairend_distro.py -r 146 -X 4 -N 10000
> -o 4048-EWSR 24048-EWSR_Merged.lib1.his
>
> And this works perfectly fine. So, hopefully thats the same issue with you
> also. I see that you are running LumpyExpress which automatically generates
> the stats for you. So, in this case you might have to go and change the
> clues in the /scripts/lumpyexpress code which is set as "tail -n+1000000"
> and sample size "N= 1000000" Try checking how many reads you have in your
> BAM file and change that accordingly.
>
> Hope this helps.
> Ashini.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/104#issuecomment-161080073>.
>



-- 
Ryan Layer

**Comment by nuin** [comment]
I just had the same error 

```python
Sourcing executables from /Users/nuin/src/lumpy-sv/bin/lumpyexpress.config ...

Checking for required python modules (/usr/local/bin/python)...
Calculating insert distributions...
Library read groups:
Library read length: 300
usage: bamfilterrg.py [-h] [-i BAM] [-r STR] [-n INT] [-S] [-b] [-u]
bamfilterrg.py: error: argument -r/--readgroup: expected one argument
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/nuin/src/lumpy-sv//scripts/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64```

**Comment by ryanlayer** [comment]
can you check to see if you are having the same file length issue?

On Fri, Apr 22, 2016 at 10:41 AM, Paulo Nuin <notifications@github.com>
wrote:

> I just had the same error
>
> Sourcing executables from /Users/nuin/src/lumpy-sv/bin/lumpyexpress.config ...
>
> Checking for required python modules (/usr/local/bin/python)...
> Calculating insert distributions...
> Library read groups:
> Library read length: 300
> usage: bamfilterrg.py [-h] [-i BAM] [-r STR] [-n INT] [-S] [-b] [-u]
> bamfilterrg.py: error: argument -r/--readgroup: expected one argument/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "/Users/nuin/src/lumpy-sv//scripts/pairend_distro.py", line 106, in <module>
>     (removed, upper_cutoff))TypeError: %d format: a number is required, not numpy.float64```
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/104#issuecomment-213502591>
>



-- 
Ryan Layer
