### ISSUE TITLE
Read Length error

### ISSUE THREAD

**Issue by abolia** [arq5x/lumpy-sv#107]
Hi, 

I am using Lumpy for finsing structural variations (Translocations) in my data set. And when I run Lumpy I get this error:

"
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/arup-storage1/tools/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 127, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/home/arup-storage1/tools/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 123, in main
    bamfilterrg(args.input, args.readgroup, args.n, args.S, args.b, args.u)
  File "/uufs/chpc.utah.edu/common/home/arup-storage1/tools/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 22, in bamfilterrg
    in_bam = pysam.Samfile("-", "r")
  File "pysam/calignmentfile.pyx", line 311, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4929)
  File "pysam/calignmentfile.pyx", line 510, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7138)
ValueError: file header is empty (mode='r') - is it SAM/BAM format?
Usage: pairend_distro.py [options]

pairend_distro.py: error: Read length not given

"
I am using LumpyExpress:
/tools/lumpy-sv/bin/lumpyexpress -B 150921-13-7876-MBC3_S2_Merged.bam -S 150921-13-7876-MBC3_S2_Merged.splitters.bam -D 150921-13-7876-MBC3_S2_Merged.discordants.bam -o 150921-13-7876-MBC3_S2.vcf

Can you please help me get around this error. 

Thanks,
Ashini.

**Comment by abolia** [comment]
I also tried specifying read length with -r option.

/tools/lumpy-sv/bin/lumpyexpress -B 150921-13-7876-MBC3_S2_Merged.sorted.bam -S 150921-13-7876-MBC3_S2_Merged.splitters.bam -D 150921-13-7876-MBC3_S2_Merged.discordants.bam -o 150921-13-7876-MBC3_S2.vcf -r 143

But still the same error.

I am thinking that, it might like having an issue parsing the @RG tag line. This is my @RG tag line:

@RG     ID:150921-13-7876-MBC3_S2       PL:ILLUMINA     PU:150921-13-7876-MBC3_S2       LB:150921-13-7876-MBC3_S2       SM:150921-13-7876-MBC3_S2       CN:ARUP

all tab delimited.

Any idea if this is what is causing the issue?
