### ISSUE TITLE
Error happened running  the l_merge.py

### ISSUE THREAD

**Issue by 54tuifeimo** [arq5x/lumpy-sv#205]
Hi! I use Lumpyexpress and got the many sample.vcf, then sort all the sample.vcf with l_sort.py and got the samples.sort.vcf. However, when i run the l_merge.py, i get the following problem. Please tell me how to solve it. Thanks!

Traceback (most recent call last):
  File "/HOME/sysu_yschen_1/program/LUMPY/lumpy-sv-0.2.13/scripts/l_merge.py", line 701, in <module>
    sys.exit(main())
  File "/HOME/sysu_yschen_1/program/LUMPY/lumpy-sv-0.2.13/scripts/l_merge.py", line 695, in main
    use_product=opts.use_product)
  File "/HOME/sysu_yschen_1/program/LUMPY/lumpy-sv-0.2.13/scripts/l_merge.py", line 611, in l_cluster
    fixed_slop=fixed_slop)
  File "/HOME/sysu_yschen_1/program/LUMPY/lumpy-sv-0.2.13/scripts/l_bp.py", line 188, in __init__
    self.p_l = [float(x) for x in m['PRPOS'].split(',')]
KeyError: 'PRPOS'

**Comment by 54tuifeimo** [comment]
I just found  when i add -P in the lumpyexpress, then the result of the vcf having the PRPOS value, then i can successully run the l_sort.py and  l_merge.py.
lumpyexpress \
    -P \
    -B sample.bam \
    -S sample.splitters.bam \
    -D sample.discordants.bam \
    -o sample.vcf

**Comment by ryanlayer** [comment]
Yep, that's it.
