### ISSUE TITLE
Error for Partial BAM

### ISSUE THREAD

**Issue by sicotte** [arq5x/lumpy-sv#250]
Hello,
         I tried running lumpy express with a BAM that has been subsetted to ONLY include chromosome 22 reads (the header lists the whole human genome). I also give it an "-x bed" exclude bed file that excludes
all chromosomes, but 22 .. and also excludes most of chromosome 22. 

The search for translocations/deletions/gains works fine using delly, but I get the following error using lumpyexpress with only the -B and -x options.

lumpyexpress -B  /research/bsi/projects/pharmacogenetics/s206438.CYP2D6/processing/RUNS/WGS/NA19174.chr22.bam -x /research/bsi/projects/pharmacogenetics/s206438.CYP2D6/LPEA_CAD_NGS_CYP2D6/external/NotD6D7D8.bed
Sourcing executables from /research/bsi/tools/biotools/lumpy-sv/0.2.13/bin/lumpyexpress.config ...

Checking for required python modules (/research/bsi/tools/biotools/python/2.7.10/bin/python)...
/research/bsi/projects/pharmacogenetics/s206438.CYP2D6/processing/RUNS/WGS/NA19174.chr22.bam.bai
/research/bsi/tools/biotools/lumpy-sv/0.2.13/bin/lumpyexpress: line 288: --acceptDupMarks: command not found
[W::hts_idx_load2] The index file is older than the data file: /research/bsi/projects/pharmacogenetics/s206438

Traceback (most recent call last):
  File "/research/bsi/tools/biotools/lumpy-sv/0.2.13//scripts/bamkit/bamgroupreads.py", line 162, in <module>
    sys.exit(main())
  File "/research/bsi/tools/biotools/lumpy-sv/0.2.13//scripts/bamkit/bamgroupreads.py", line 158, in main
    bamgroupreads(args.input, args.readgroup, args.reset_dups, args.fix_flags, args.S, args.b, args.u)
  File "/research/bsi/tools/biotools/lumpy-sv/0.2.13//scripts/bamkit/bamgroupreads.py", line 91, in bamgroupreads
    out_bam.write(al)
  File "pysam/libcalignmentfile.pyx", line 1653, in pysam.libcalignmentfile.AlignmentFile.write
  File "pysam/libcalignmentfile.pyx", line 1682, in pysam.libcalignmentfile.AlignmentFile.write
IOError: sam_write1 failed with error code -1
/research/bsi/tools/biotools/python/2.7.10/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/research/bsi/tools/biotools/python/2.7.10/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/research/bsi/tools/biotools/lumpy-sv/0.2.13//scripts/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64

**Comment by sicotte** [comment]
H

**Comment by sicotte** [comment]
Looks like it's an installation issue, SAMBLASTER was not installed.. I'll check with our IT group.
