### ISSUE TITLE
lumpyexpress finishes without result

### ISSUE THREAD

**Issue by arkyl** [arq5x/lumpy-sv#252]
Hi, 
I ran the following cmd:
 lumpyexpress -B ERR194147.bam -D ERR194147.bam.discordants.sort.bam -o output.vcf

The  lumpyexpress finished within a few minutes without error message, but there is no output.vcf. I can run traditional lumpy and get a result. The bam has no split read info so only discordant pair bam was used. Any thought about this? Thanks very much.

**Comment by ryanlayer** [comment]
Does the BAM have read groups?

**Comment by arkyl** [comment]
Yes.
@RG     ID:ERR194147_0  LB:ERR194147    PU:0    SM:ERR194147
Thanks for the fast reply.

**Comment by ryanlayer** [comment]
Can you paste in the output from lumpyexpress?

**Comment by arkyl** [comment]
Hi,
Here is the output:

Sourcing executables from /home/liuy/software_installed/lumpy-sv/scripts/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...
Calculating insert distributions... 
Library read groups: ERR194147_0
Library read length: 101
Removed 77 outliers with isize >= 781
done

It stays at line "Library read length: 101" for a few minutes. Then stderr "Removed 77 outliers with isize >= 781" and "done". But no output.vcf.

Thanks much.

**Comment by ryanlayer** [comment]
Can you rerun with "-v" to get more output?

**Comment by arkyl** [comment]
Hi,
I reran with -v (lumpyexpress -v -B ERR194147.bam -D ERR194147.bam.discordants.sort.bam -o output.vcf), but still get the same result:

Sourcing executables from /home/liuy/software_installed/lumpy-sv/scripts/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...

    create temporary directory
Calculating insert distributions... 
Library read groups: ERR194147_0
Library read length: 101
Removed 77 outliers with isize >= 781
done

**Comment by carleshf** [comment]
The same problem happened here:

```
lumpyexpress -v \
>     -B DN_bwa_b38_recal_leftalignindels_chr22.bam \
>     -S DN_bwa_b38_recal_leftalignindels_chr22.splitters.bam \
>     -D DN_bwa_b38_recal_leftalignindels_chr22.discordants.bam \
>     -o DN_bwa_b38_recal_leftalignindels_chr22.lumpyexpress.vcf
```

I put some "echo"s into the code and found that the execution stops at the command used to fill "SPL_SAMPLE".

```
SPL_SAMPLE=`$SAMT view -H $SPL_BAM | grep -m 1 "^@RG" | gawk -v i=$i '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'`
```

I tested the same run in WES and it worked but with WGS it is not generating the output.

**Comment by carleshf** [comment]
I extract the command from the Perl source file and run it in shell:

```
$ samtools view -H DN_bwa_b38_recal_leftalignindels_chr22.splitters.bam | grep -m 1 "^@RG" | gawk -v i=0 '{ for (j=1;j<=NF;++j) {if ($j~"^SM:") { gsub("^SM:","",$j); print $j } } }'
DN
```

So, I do not see why the script is stopping while or after running the command. But the "echo" printing the content of "SPL_SAMPLE" I put after it is not shown.

**Comment by carleshf** [comment]
Using the version distributed with `seepseq` (lumpy-sv @ dd4bf97) solved the problem (once removed "check_sq=False” from `bamlibs.py`).

**Comment by SilenWang** [comment]
I'm using lumpy-sv v0.2.14a distibuted on [bioconda](https://anaconda.org/bioconda/lumpy-sv). And when I run the following code, there were some error:

```bash
#### My code ####
SAMPLE=sample
BAM_PATH=/path/to/bam/file

lumpyexpress \
    -B ${BAM_PATH}/${SAMPLE}.bam \
    -S ${SAMPLE}.splitters.bam \
    -D ${SAMPLE}.discordants.bam \
    -o ${SAMPLE}.vcf

#### Output I got ####
Sourcing executables from /path/to/lumpyexpress.config ...

Checking for required python modules (/path/to/python)...
/path/to/lumpyexpress: line 15: -n: command not found
/path/to/lumpyexpress: line 16: [: ==: unary operator expected
Traceback (most recent call last):
  File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 79, in <module>
    sys.exit(main())
  File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 74, in main
    get_libs(args.input, args.is_sam, True)
  File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 44, in get_libs
    in_bam = pysam.Samfile(bam, 'rb', check_sq=False)
  File "csamtools.pyx", line 463, in csamtools.Samfile.__cinit__ (pysam/csamtools.c:4758)
  File "csamtools.pyx", line 476, in csamtools.Samfile._open (pysam/csamtools.c:5052)
TypeError: _open() got an unexpected keyword argument 'check_sq'
```

I solved the first error in lumpyexpress line 15 & 16 by adding the following line to `lumpyexpress.config`
```
HEXDUMP=`which hexdump || true`
```

And the `TypeError` was solved accoding to @carleshf 's reply.

**Comment by ryanlayer** [comment]
Can you rerun with those fixes and send the new error?

**Comment by SilenWang** [comment]
Emmmm, now lumpyexpress run without any problem, and the result seems to be fine.

> Can you rerun with those fixes and send the new error?
> […](#)
> On Oct 23, 2018, at 2:44 AM, SilenWang ***@***.***> wrote: I'm using lumpy-sv v0.2.14a distibuted on bioconda. And when I run the following code, there were some error: #### My code #### SAMPLE=sample BAM_PATH=/path/to/bam/file lumpyexpress \ -B ${BAM_PATH}/${SAMPLE}.bam \ -S ${SAMPLE}.splitters.bam \ -D ${SAMPLE}.discordants.bam \ -o ${SAMPLE}.vcf #### Output I got #### Sourcing executables from /path/to/lumpyexpress.config ... Checking for required python modules (/path/to/python)... /path/to/lumpyexpress: line 15: -n: command not found /path/to/lumpyexpress: line 16: [: ==: unary operator expected Traceback (most recent call last): File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 79, in <module> sys.exit(main()) File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 74, in main get_libs(args.input, args.is_sam, True) File "/path/to/lumpy-sv-0.2.14a-2/scripts/bamkit/bamlibs.py", line 44, in get_libs in_bam = pysam.Samfile(bam, 'rb', check_sq=False) File "csamtools.pyx", line 463, in csamtools.Samfile.__cinit__ (pysam/csamtools.c:4758) File "csamtools.pyx", line 476, in csamtools.Samfile._open (pysam/csamtools.c:5052) TypeError: _open() got an unexpected keyword argument 'check_sq' I solved the first error in lumpyexpress line 15 & 16 by adding the following line to lumpyexpress.config HEXDUMP=`which hexdump || true` And the TypeError was solved accoding to @carleshf 's reply. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
