### ISSUE TITLE
Error while running lumpyexpress

### ISSUE THREAD

**Issue by adily777** [arq5x/lumpy-sv#334]
Hello,

I tried to run lumpyexpress by the next command:
`lumpyexpress -B 7628_R1.bam -o lumpy.7628.vcf -x b37.bed -k`

And I got the next error:
```
Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...
[W::hts_idx_load2] The index file is older than the data file: 7628_R1.bai
/usr/local/bin/lumpyexpress: line 389: --acceptDupMarks: command not found
[main_samview] fail to read the header from "/dev/stdin".
Warning: only 0 elements in distribution (min: 1000)
[W::hts_idx_load2] The index file is older than the data file: ../check_arcsv/7628/7628_R1.conc.hs37d5.aligned.duplicates_marked.recalibrated.bai
Traceback (most recent call last):
  File "/home/dolevr/Documents/adily/lumpy-sv//scripts/bamkit/bamgroupreads.py", line 171, in <module>
    sys.exit(main())
  File "/home/dolevr/Documents/adily/lumpy-sv//scripts/bamkit/bamgroupreads.py", line 167, in main
    bamgroupreads(args.input, args.readgroup, args.reset_dups, args.fix_flags, args.S, args.b, args.u)
  File "/home/dolevr/Documents/adily/lumpy-sv//scripts/bamkit/bamgroupreads.py", line 93, in bamgroupreads
    out_bam.write(al)
  File "pysam/libcalignmentfile.pyx", line 1698, in pysam.libcalignmentfile.AlignmentFile.write
  File "pysam/libcalignmentfile.pyx", line 1727, in pysam.libcalignmentfile.AlignmentFile.write
IOError: sam_write1 failed with error code -1
```
What can be the reason for that?

Regards,
Adily

**Comment by adily777** [comment]
I tried to use lower version of pysam till I get to 0.9v, only than I didn't get the IOError: sam_write1 failed with error code -1.

But still, there is a problem.
I got this:
```
Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...
/usr/local/bin/lumpyexpress: line 389: --acceptDupMarks: command not found
[main_samview] fail to read the header from "/dev/stdin".
Warning: only 0 elements in distribution (min: 1000)
```
And It seems to keep running but never finished. 
An output folder was created with some empty files and a vcf (lumpy.7628.vcf.sample1.lib1.insert.stats) file that contain one line:
mean:NA	stdev:NA

What is the problem?
Adily
