### ISSUE TITLE
lumpyexpress error

### ISSUE THREAD

**Issue by assane-mbodj** [arq5x/lumpy-sv#359]
Hello I am new in programming and I wanted to test lumpy on my Arabodopsis data
When I run lumpyexpress I get this error 

$lumpyexpress -B file.sorte.bam -S file.splitters.sorted.bam -D file.discordants.sorted.bam -o file.vcf
Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/home/assane/anaconda3/envs/hecaton_py2/bin/python)...
Calculating insert distributions... 
/home/assane/anaconda3/envs/hecaton_py2/bin/samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Library read groups: id
Library read length: 0
/home/assane/anaconda3/envs/hecaton_py2/bin/samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Usage: pairend_distro.py [options]

pairend_distro.py: error: Read length not given
Traceback (most recent call last):
  File "/home/assane/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 127, in <module>
    sys.exit(main())
  File "/home/assane/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 123, in main
    bamfilterrg(args.input, args.readgroup, args.n, args.S, args.b, args.u)
  File "/home/assane/lumpy-sv//scripts/bamkit/bamfilterrg.py", line 24, in bamfilterrg
    in_bam = pysam.Samfile('-', 'rb')
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 947, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data

Can someone help me please

**Comment by ryanlayer** [comment]
Looks like an issues with your samtools. See

https://github.com/merenlab/anvio/issues/1479

**Comment by assane-mbodj** [comment]
Hello

I want to test lumpy on two samples at the same time but it doesn't work.
It doesn't find the indexed files even though I have them.

Here is the output

assane@gwas:~/lumpy-sv/output_PO10C$ lumpyexpress -B PO10A.sorted.bam,PO10C.sorted.bam -S PO10A.splitters.sorted.bam,PO10C.splitters.sorted.bam -D PO10A.discordants.sorted.bam,PO10C.discordants.sorted.bam -o multi_PO10.vcf
Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...
Calculating insert distributions... 
Library read groups: id
Library read length: 150
[E::idx_find_and_load] Could not retrieve index file for '-'
Removed 1233 outliers with isize >= 924
done
1
Calculating insert distributions... 
Library read groups: id
Library read length: 150
[E::idx_find_and_load] Could not retrieve index file for '-'
Removed 1630 outliers with isize >= 1097
done
1
Running LUMPY... 
697	0
Could not open input BAM files: BamMultiReader::Open: unable to open inconsistent files: 	
BamMultiReader::ValidateReaders: mismatched references found inPO10C.discordants.sorted.bamexpected: 
but found: 



Thank you for your help

**Comment by yefanglee** [comment]
> 

I met the same error as yours, I wonder did you solve it?

Could not open input BAM files: BamMultiReader::Open: unable to open all files:         
        unable to open file: data/LPY26.disc.bam
        unable to open file: data/LPY26.spli.bam
        unable to open file: data/LSD13.disc.bam
        unable to open file:data/LSD13.spli.bam
