### ISSUE TITLE
Error with lumpy-sv/scripts/get_coverages.py

### ISSUE THREAD

**Issue by chad388** [arq5x/lumpy-sv#83]
Hi,

I am attempting to create an exclude bedfile using get_coverage.py and get_exclude_regions.py scripts from the Lumpy package. I ran lumpy on a set of 17 samples using speedseq realign and then speedseq sv and then I used bamtools merge to merge the 17 discordant bams into a single bam and to merge the 17 splitter bams into a single bam. I then used bamtools to sort and index the merged bams. I then attempted to run get_coverage.py on the merged bamfiles, but I get the error below related to the merged discordants file:

lumpy-sv/scripts/get_coverages.py MERGED.discordants_SORTED.bam

Traceback (most recent call last):
  File
/lumpy-sv/scripts/get_coverages.py",
line 56, in <module>
    if int(a[3]) > 0:
ValueError: invalid literal for int() with base 10: '1.01462e+06'

Do you know what the reason for this error might be? I re-merged and resorted all of the discordants bams again, but I still encounter this error.

Thanks,
Chad

**Comment by chad388** [comment]
Ryan, do you have any ideas why I might be getting this ValueError: invalid literal for int() with base 10: '1.01462e+06' when trying to run get_coverages.py on the merged bamfile from this?

**Comment by ryanlayer** [comment]
You should be creating your coverage file from you original bam, not your
discordance file.

The thing that confuses me about your error though is that there is a
near-zero float in your coverage file.  Do you have a file named
"MERGED.discordants_SORTED.bam.genome"?
If so, can you check to see where that "1.01462e+06" is coming from?  This
may be an issue with bedtools genomecov.

On Wed, Jun 17, 2015 at 7:51 PM, chad388 <notifications@github.com> wrote:

> Ryan, do you have any ideas why I might be getting this ValueError:
> invalid literal for int() with base 10: '1.01462e+06' when trying to run
> get_coverages.py on the merged bamfile from this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/83#issuecomment-112981899>.
>



-- 
Ryan Layer

**Comment by chad388** [comment]
Hi Ryan,

I went back and merged together the original bams from all 17 samples, I upgraded bedtools to V2.24, and then ran get_coverages.py on the merged bamfile, but I am still encountering a similar near-zero float point error. The merged bam is 1.4TB in size and I am not sure if the large size could be contributing to this issue:

Traceback (most recent call last):
  File "/gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_coverages.py", line 56, in <module>
    if int(a[3]) > 0:
ValueError: invalid literal for int() with base 10: '1.24585e+06'

The .genome file was created and the contents are listed below, but I am not sure how to correlate the contents of that file to this error above. The process runs for ~28 hrs and then crashes with the error above:

1	126035930
2	90373283
3	92142175
4	91010382
5	75399963
6	50890351
7	135778131
8	139301422
9	125710982
10	128595539
11	128539186
12	108555830
13	98384682
14	107702431
15	91754291
16	75148670
17	71996105
18	72318688
19	33263144
20	130588469
21	127223203
22	101219884
23	82825804
24	84932903
25	85787240
26	58131712
27	48547382
28	21531802
29	24206276
30	130038232
31	6181219

If I then attempt to run get_exclude_regions.py on the truncated output from the previous step, I get the error below:

python /gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_exclude_regions.py 10 vervet_17_sample_exclude_10.bed VERVET_ALL_17_REGULAR_BAMS_MERGED.bam
Traceback (most recent call last):
  File "/gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_exclude_regions.py", line 23, in <module>
    if (int(a[3]) > max_c):
ValueError: invalid literal for int() with base 10: '1.24585e+06'

Thanks,
Chad

**Comment by ryanlayer** [comment]
I just pushed a change to parse the input as float, not it.  Please give it
a try and let me know.

On Thu, Jul 9, 2015 at 1:05 PM, chad388 <notifications@github.com> wrote:

> Hi Ryan,
>
> I went back and merged together the original bams from all 17 samples, I
> upgraded bedtools to V2.24, and then ran get_coverages.py on the merged
> bamfile, but I am still encountering a similar near-zero float point error.
> The merged bam is 1.4TB in size and I am not sure if the large size could
> be contributing to this issue:
>
> Traceback (most recent call last):
> File
> "/gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_coverages.py",
> line 56, in
> if int(a[3]) > 0:
> ValueError: invalid literal for int() with base 10: '1.24585e+06'
>
> The .genome file was created and the contents are listed below, but I am
> not sure how to correlate the contents of that file to this error above.
> The process runs for ~28 hrs and then crashes with the error above:
>
> 1 126035930
> 2 90373283
> 3 92142175
> 4 91010382
> 5 75399963
> 6 50890351
> 7 135778131
> 8 139301422
> 9 125710982
> 10 128595539
> 11 128539186
> 12 108555830
> 13 98384682
> 14 107702431
> 15 91754291
> 16 75148670
> 17 71996105
> 18 72318688
> 19 33263144
> 20 130588469
> 21 127223203
> 22 101219884
> 23 82825804
> 24 84932903
> 25 85787240
> 26 58131712
> 27 48547382
> 28 21531802
> 29 24206276
> 30 130038232
> 31 6181219
>
> If I then attempt to run get_exclude_regions.py on the truncated output
> from the previous step, I get the error below:
>
> python
> /gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_exclude_regions.py
> 10 vervet_17_sample_exclude_10.bed VERVET_ALL_17_REGULAR_BAMS_MERGED.bam
> Traceback (most recent call last):
> File
> "/gscmnt/gc6149/assembly/Downloads/Lumpy/lumpy-sv/scripts/get_exclude_regions.py",
> line 23, in
> if (int(a[3]) > max_c):
> ValueError: invalid literal for int() with base 10: '1.24585e+06'
>
> Thanks,
> Chad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/83#issuecomment-120071901>.
>



-- 
Ryan Layer

**Comment by chad388** [comment]
I wanted to update, that I get the "ValueError: invalid literal for int() with base 10" when running the updated version of get_coverages.py on this dataset, but I determined that the error is due to some coverage outputs from bedtools genomecov being expressed in scientific notation. After converting any coverage values expressed as scientific notation to regular numbers, get_exclude_regions.py runs on the .coverage files without any issues.

**Comment by ryanlayer** [comment]
Hey Chad,

Are you sure that you are using the latest version of get_exclude_regions?
I pushed a change to get_coverages.py on Jul 9 that _should_ have fixed
this.

Ryan

On Mon, Aug 31, 2015 at 12:34 PM, chad388 <notifications@github.com> wrote:

> I wanted to update, that I get the "ValueError: invalid literal for int()
> with base 10" when running the updated version of get_coverages.py on this
> dataset, but I determined that the error is due to some coverage outputs
> from bedtools genomecov being expressed in scientific notation. After
> converting any coverage values expressed as scientific notation to regular
> numbers, get_exclude_regions.py runs on the .coverage files without any
> issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/83#issuecomment-136456654>.
>



-- 
Ryan Layer
