### ISSUE TITLE
error removing reads

### ISSUE THREAD

**Issue by calkan** [arq5x/lumpy-sv#94]
Hi @ryanlayer , reopening issue #56 . I have the same problem
(v 0.2.11)

lumpyexpress -B HG00096.recal.bam -o HG00096.vcf

BAM file:

http://alkanlab.org/share/lumpy/

**Comment by ryanlayer** [comment]
Would it be possible to 1) slice this BAM up so that only the offending region is include (+- 100KB of the region in the error should be fine and 2) upload the histo file (if you still have it laying around)

**Comment by calkan** [comment]
@canfirtina is on it...

**Comment by ryanlayer** [comment]
Can y'all try the latest version?

**Comment by canfirtina** [comment]
Hi @ryanlayer ,

We tried both with the latest release version and latest version as you indicated.

With the release version we get this error:

Error removing element:7,135785114,135785050,+  7,135785125,135785061,- 1
/mnt/compgen/inhouse/bin/lumpyexpress: line 411: 53857 Aborted                 (core dumped) $LUMPY $PROB_CURVE -t ${TEMP_DIR}/${OUTBASE} -msw $MIN_SAMPLE_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $OUTPUT

With the latest version the error is different actually:

/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Removed 0.000000 outliers with isize >= nan
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:91: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:113: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan 4.000000 nan
Traceback (most recent call last):
  File "/home/cfirtina/lumpy/lumpy-sv/scripts/pairend_distro.py", line 115, in <module>
    end = int(mean + options.X*stdev)
ValueError: cannot convert float NaN to integer


Actually this was not the actual error that we get with the latest version. I modified it little bit. In the same file (pairend_distro.py), there was an conversion problem on line 105 of pairend_distro.py. I changed %d format to %f and now we get the problem indicated above. I believe this error shows the problem with pairend_distro.py clearly. It might be possible that "mean" or "stdev" is being divided by zero (or something empty) at some point so we get this error.

You can find the related files under http://alkanlab.org/share/lumpy/

**Comment by Nymeria8** [comment]
I have exactly the same error... There is already a way to solve it?

**Comment by ryanlayer** [comment]
Okay, I finally got to the bottom of this.  How did you align this?  You
have the following alignment (note the CIGAR string)

SRR062634.15200418      83      7       135785051       70      34S66I

Regardless, the latest revision in github should work for y'all.



On Wed, Sep 16, 2015 at 8:36 AM, Can <notifications@github.com> wrote:

> Hi @ryanlayer <https://github.com/ryanlayer> ,
>
> We tried both with the latest release version and latest version as you
> indicated.
>
> With the release version we get this error:
>
> Error removing element:7,135785114,135785050,+ 7,135785125,135785061,- 1
> /mnt/compgen/inhouse/bin/lumpyexpress: line 411: 53857 Aborted (core
> dumped) $LUMPY $PROB_CURVE -t ${TEMP_DIR}/${OUTBASE} -msw
> $MIN_SAMPLE_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING
> $LUMPY_SPL_STRING > $OUTPUT
>
> With the latest version the error is different actually:
>
> /usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:55:
> RuntimeWarning: Mean of empty slice.
> warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:67:
> RuntimeWarning: invalid value encountered in double_scalars
> ret = ret.dtype.type(ret / rcount)
> Removed 0.000000 outliers with isize >= nan
> /usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:79:
> RuntimeWarning: Degrees of freedom <= 0 for slice
> warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:91:
> RuntimeWarning: invalid value encountered in true_divide
> arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
> /usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:113:
> RuntimeWarning: invalid value encountered in double_scalars
> ret = ret.dtype.type(ret / rcount)
> nan 4.000000 nan
> Traceback (most recent call last):
> File "/home/cfirtina/lumpy/lumpy-sv/scripts/pairend_distro.py", line 115,
> in
> end = int(mean + options.X*stdev)
> ValueError: cannot convert float NaN to integer
>
> Actually this was not the actual error that we get with the latest
> version. I modified it little bit. In the same file (pairend_distro.py),
> there was an conversion problem on line 105 of pairend_distro.py. I changed
> %d format to %f and now we get the problem indicated above. I believe this
> error shows the problem with pairend_distro.py clearly. It might be
> possible that "mean" or "stdev" is being divided by zero (or something
> empty) at some point so we get this error.
>
> You can find the related files under http://alkanlab.org/share/lumpy/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/94#issuecomment-140760898>.
>



-- 
Ryan Layer

**Comment by ryanlayer** [comment]
Please check the latest from git hub and let me know if you issues is still
not fixed.

On Mon, Oct 26, 2015 at 6:08 AM, Joana Fino <notifications@github.com>
wrote:

> I have exactly the same error... There is already a way to solve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/94#issuecomment-151113695>.
>



-- 
Ryan Layer

**Comment by Nymeria8** [comment]
Thank you for the reply. I tried the new version and the result was exactly the same.

I used speedseq for the alignment:
speedseq align -o speedseq_test -R "@RG\tID:NA12878\tSM:NA12878\tLB:lib1" -t 3 ../../genome_index/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa ../../raw_data/R1.fq.gz ../../raw_data/R2.fq.gz

I already checked my versions of the dependencies, and they all match the requirements.

**Comment by ryanlayer** [comment]
I will have to get the speedseq authors to update the version of lumpy they
use.

On Mon, Oct 26, 2015 at 1:08 PM, Joana Fino <notifications@github.com>
wrote:

> Thank you for the reply. I tried the new version and the result was
> exactly the same.
>
> I used speedseq for the alignment:
> speedseq align -o speedseq_test -R "@RG <https://github.com/RG>\tID:NA12878\tSM:NA12878\tLB:lib1"
> -t 3 ../../genome_index/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
> ../../raw_data/R1.fq.gz ../../raw_data/R2.fq.gz
>
> I already checked my versions of the dependencies, and they all match the
> requirements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/94#issuecomment-151252533>.
>



-- 
Ryan Layer

**Comment by cc2qe** [comment]
I've updated it with https://github.com/hall-lab/speedseq/commit/c1058b7053ef055521af0aa3d39197088168d07a

the following commands in the speedseq directory should update the submodules
```
git submodule update --init
make sv
```

**Comment by Nymeria8** [comment]
I dont know if i explained myself well.. I only did the alignment with speedseq, and runned lumpy separately with the new github version...

**Comment by ryanlayer** [comment]
Please send me the exact lumpy command, histo file, and a slice of your bam
that contains the error.

On Mon, Oct 26, 2015 at 1:23 PM, Joana Fino <notifications@github.com>
wrote:

> I dont know if i explained myself well.. I only did the alignment with
> speedseq, and runned lumpy separately with the new github version...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/lumpy-sv/issues/94#issuecomment-151256111>.
>



-- 
Ryan Layer

**Comment by Nymeria8** [comment]
I used lumpyexpress:
~/software/lumpy-sv/bin/lumpyexpress -B speedseq_test.bam -D speedseq_test.discordants.bam -o clusts.vcf -v -K lumpyexpress.config
 
So I dont have histo file or bam slice...

**Comment by canfirtina** [comment]
the same error still persists with the latest version

**Comment by cc2qe** [comment]
@Nymeria8 , since you aligned with speedseq, try adding the -S splitters.bam argument to your lumpyexpress command. If you still get an error, please copy the screen output of speedseq here, since speedseq prints all its internal commands.

I think that all of these issues are related to running lumpyexpress without both the -S and -D inputs.

**Comment by Nymeria8** [comment]
Thank you for the feedback!
So, after the speedseq run I checked the outputs, and the splitters.bam was empty, so I didnt use it on lumpy. Anyway, I ran speedseq sv with the new lumpy version, and the results were still the same:

 ~/software/speedseq/bin/speedseq sv -B speedseq_test.bam -S speedseq_test.splitters.bam -D speedseq_test.discordants.bam -R ../../genome_index/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa -o teste -t 1 -K ~/software/speedseq/bin/speedseq.config
Sourcing executables from /home/joanafino/software/speedseq/bin/speedseq.config ...

Checking for required python modules (/usr/bin/python2.7)...

Running LUMPY express
Sourcing executables from /home/joanafino/software/speedseq/bin/speedseq.config ...

Checking for required python modules (/usr/bin/python2.7)...

    create temporary directory
Calculating insert distributions...
Library read groups: NA12878
Library read length: 25
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:91: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:113: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/joanafino/software/lumpy-sv/scripts/pairend_distro.py", line 113, in <module>
    end = int(mean + options.X*stdev)
ValueError: cannot convert float NaN to integer

**Comment by cc2qe** [comment]
looks like LUMPY is unable to produce the histogram from your discordants file. If you send the first 10000 lines of your discordants.bam, it'll probably tell us why.

Also, looks like you are using 25 bp reads. We have not tested LUMPY on this library design to my knowledge.

**Comment by Nymeria8** [comment]
Here is my discordants file: https://transfer.sh/4ThRG/discord

Thank you for the information! I will try it anyway, i'm curious about the results.

**Comment by ryanlayer** [comment]
@calkan What version of pysam do you have installed?

**Comment by Nymeria8** [comment]
pysam-0.8.4

**Comment by calkan** [comment]
0.8.0  for me.

**Comment by ryanlayer** [comment]
@calkan I am at a bit of a loss as to what is going wrong on your end.  It could be your version of pysam.  I have 0.8.3 and I get the following result:

```
lumpy-sv/scripts/lumpyexpress -B HG00096.recal.bam
Sourcing executables from lumpy-sv/scripts/lumpyexpress.config ...

Checking for required python modules (/usr/local/bin/python)...
samblaster: Version 0.1.21
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening HG00096.recal.bam.vcf.r1Hp08z6O5Fc/disc_pipe for write.
samblaster: Opening HG00096.recal.bam.vcf.r1Hp08z6O5Fc/spl_pipe for write.
samblaster: Loaded 84 header sequence entries.
```

And things proceed normally from there.  Can you try upgrading and then rerunning?

**Comment by ryanlayer** [comment]
@Nymeria8 what type of file is "discord"? When I down load it there is not extension and I cannot get samtools to view the file.

**Comment by Nymeria8** [comment]
oh, sorry, i forgot the file extension. its a tar.gz file...

**Comment by ryanlayer** [comment]
@Nymeria8 can you provide speedseq_test.bam too?

**Comment by Nymeria8** [comment]
I am sending only the chromosome 1 part of the alignment, the complete file is huge!
https://transfer.sh/jfTab/chr1.bam

**Comment by Nymeria8** [comment]
ok, i have been trying to fix this, and, if i understood correctly, the problem comes from the way lumpyExpress give the arguments to pairend_distro.py.
I tried to run pairend_distro.py separatly to analyse the error, and, in that way, the script runned with no errors.

**Comment by ryanlayer** [comment]
@Nymeria8 What kind of library is this?

**Comment by Nymeria8** [comment]
Mate-pair

**Comment by ryanlayer** [comment]
@Nymeria8 That's the issue.  Lumpy works off paired-end and split-read signal only.  Sorry.

**Comment by calkan** [comment]
I'll try with updated pysam when I manage to make myself to work on python crap. Why do you use python libraries anyway? I thought you were a good coder.

**Comment by canfirtina** [comment]
Hi @ryanlayer ,

We have updated pysam to 0.9.0 and pulled the latest commit from github/master for lumpy. Apparently it does not crash anymore. However, we still get a segmentation fault with the high coverage data (HG02107) but it still manages to create the vcf files properly. The error given as follows:

lumpyexpress: line 413: 29071 Segmentation fault      (core dumped) $LUMPY $PROB_CURVE -t ${TEMP_DIR}/${OUTBASE} -msw $MIN_SAMPLE_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $OUTPUT

There was no segmentation fault when we created the vcf files for the low coverage data (HG00096).

The related bam files can be found at: http://alkanlab.org/paper-data/reproducibility/
